
import { PlaceHolderImages, type ImagePlaceholder } from './placeholder-images';

export type ProductCategory =
  | 'AHD Camera'
  | 'IP Camera'
  | 'Special Camera'
  | 'DVR'
  | 'NVR'
  | 'Poe Switch'
  | 'Wire'
  | 'Rack'
  | 'Power Supply'
  | 'Accessories'
  | 'Video Door Phone'
  | 'Biometric Device';


export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  description: string;
  image: ImagePlaceholder;
}

const getImage = (id: string) => {
    const image = PlaceHolderImages.find(img => img.id === id);
    if (!image) {
        // Fallback to a generic camera image if not found.
        const fallbackImage = PlaceHolderImages.find(img => img.id === 'product-camera');
        if (fallbackImage) return fallbackImage;
        // If even that fails, throw an error, but it shouldn't.
        throw new Error(`Image with id ${id} not found and fallback failed.`);
    }
    return image;
}

export const products: Product[] = [
  {
    id: 'prod-011',
    name: '2.4 MP AHD CV Plastic Dome (AS-2.4-HK-DM)',
    category: 'AHD Camera',
    price: 0,
    description: 'A plastic dome camera designed for general surveillance with AHD technology. Main Highlights: 2.4MP Resolution, 3.6mm Lens, 4 Array Color',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-012',
    name: '2.4 MP AHD IR Bullet (AS-2.4MP-HK-BT)',
    category: 'AHD Camera',
    price: 0,
    description: 'A plastic bullet camera offering standard infrared capabilities for day and night monitoring. Main Highlights: 2.4MP Resolution, 3.6mm Lens, 4',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-013',
    name: '2.4 MP AHD CV Dome Starlight (AS-2.4MP-DH-CV-DM)',
    category: 'AHD Camera',
    price: 0,
    description: 'A dome camera featuring Starlight technology for better low-light performance in a plastic DH housing. Main Highlights: 2.4MP Resolution, Starlight,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-014',
    name: '2.4 MP AHD CV Bullet Starlight (AS-2.4MP-DH-CV-BT)',
    category: 'AHD Camera',
    price: 0,
    description: 'A plastic bullet camera with TPL housing and Starlight technology for enhanced night vision. Main Highlights: 2.4MP Resolution, Starlight, 3.6mm',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-015',
    name: '2.4 MP AHD CV Audio Dome (AS-2.4MP-AUD-CV-DM)',
    category: 'AHD Camera',
    price: 0,
    description: 'An AHD dome camera equipped with a built-in microphone for audio recording over TVI format. Main Highlights: 2.4MP Resolution, Built-in',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-016',
    name: '2.4 MP AHD CV Audio Bullet (AS-2.4MP-AUD-CV-BT)',
    category: 'AHD Camera',
    price: 0,
    description: 'A bullet camera featuring audio capabilities and color vision, compatible with TVI audio support. Main Highlights: 2.4MP Resolution, Built-in Mic,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-017',
    name: '5 MP AHD CV Audio Dome (AS-5MP-AUD-CV-DM)',
    category: 'AHD Camera',
    price: 0,
    description: 'High-resolution 5MP dome camera with Starlight tech and integrated audio support. Main Highlights: 5MP Resolution, Starlight, TVI Color Audio.',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-018',
    name: '5 MP AHD CV Audio Bullet (AS-5MP-AUD-CV-BT)',
    category: 'AHD Camera',
    price: 0,
    description: 'High-resolution 5MP bullet camera delivering clear video and audio recording via TVI format. Main Highlights: 5MP Resolution, Starlight, Built-in Mic.',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-019',
    name: '4 MP IP CV Audio Dome (AS-4MP-IP-CV-DM)',
    category: 'IP Camera',
    price: 0,
    description: 'An IP-based dome camera with Starlight capabilities and ONVIF support for broader compatibility. Main Highlights: 4MP Resolution, ONVIF Supported, IR',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-020',
    name: '4 MP IP CV Audio Bullet (AS-4MP-IP-CV-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Full metal body IP bullet camera designed for durability and high-quality 4MP imaging. Main Highlights: 4MP Resolution, Full Metal Body,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-021',
    name: '5 MP IP Lite CV Audio Dome (AS-5MP-IP-CV-DM)',
    category: 'IP Camera',
    price: 0,
    description: 'A 5MP IP dome camera with a front metal housing and Starlight technology. Main Highlights: 5MP Resolution, Front Metal, ONVIF',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-022',
    name: '5 MP IP Lite CV Audio Bullet (AS-5MP-IP-CV-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Full metal IP bullet camera offering 5MP resolution and reliable night vision. Main Highlights: 5MP Resolution, Full Metal, IR Range',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-023',
    name: '5 MP IP CV 2-Way Bullet (AS-5MP-IP-CV-2WAY-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Advanced IP bullet camera featuring 2-way communication for interactive monitoring. Main Highlights: 5MP Resolution, 2-Way Audio, Starlight.',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-024',
    name: '5 MP IP CV 2-Way Dome (AS-5MP-IP-CV-2WAY-DM)',
    category: 'IP Camera',
    price: 0,
    description: 'IP dome camera with 2-way audio communication capabilities. Main Highlights: 5MP Resolution, 2-Way Audio, ONVIF Supported.',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-025',
    name: '5 MP IP Premium CV Audio Dome (AS-5MP-IP-CV-DM)',
    category: 'IP Camera',
    price: 0,
    description: 'Premium series 5MP IP dome camera with front metal housing and Starlight sensor. Main Highlights: 5MP Resolution, Starlight, Front Metal',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-026',
    name: '5 MP IP Premium CV Audio Bullet (AS-5MP-IP-CV-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Premium series 5MP IP bullet camera offering high-definition surveillance with audio. Main Highlights: 5MP Resolution, Starlight, ONVIF Supported.',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-027',
    name: '8 MP IP CV Audio Dome (AS-8MP-IP-CV-DM)',
    category: 'IP Camera',
    price: 0,
    description: 'Ultra-high resolution 8MP IP dome camera with front metal housing for superior detail. Main Highlights: 8MP Resolution, Front Metal, Starlight',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-028',
    name: '8 MP IP CV Audio Bullet (AS-8MP-IP-CV-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Full metal 8MP IP bullet camera delivering 4K quality images and audio. Main Highlights: 8MP Resolution, Full Metal, IR Range',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-029',
    name: '5 MP 5X IP CV Audio Bullet (AS-5MP-IP-5X-CV-VF-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'Full metal IP bullet camera with a variable focus lens allowing for 5X zoom. Main Highlights: 5MP Resolution, 5X Zoom',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-030',
    name: '5 MP 36X IP CV Audio PTZ (AS-5MP-IP-CV-PTZ-36X-BT)',
    category: 'IP Camera',
    price: 0,
    description: 'A powerful PTZ camera with massive 36X zoom and long-range IR for wide area coverage. Main Highlights: 5MP Resolution, 36X',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-031',
    name: '4G Solar 3MP PT (AS-4G-3MP-SOLAR)',
    category: 'Special Camera',
    price: 0,
    description: 'A wire-free 4G PT camera powered by solar energy, ideal for remote locations without power. Main Highlights: 3MP Resolution, Solar',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-032',
    name: '3 MP Wi-Fi 10X Robo (AS-10X-WIFI-3MP-ROBO)',
    category: 'Special Camera',
    price: 0,
    description: 'A dual-lens Wi-Fi robot camera featuring 10X zoom and 360-degree rotation. Main Highlights: 10X Zoom, Dual Camera, Human Tracking, 360',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-033',
    name: '3 MP Wi-Fi Lamp (AS-WIFI-2MP-LAMP)',
    category: 'Special Camera',
    price: 0,
    description: 'A discreet lamp camera that fits into a light socket, offering panoramic monitoring and tracking. Main Highlights: Motion Tracking, Pan-Tilt,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-034',
    name: '3 MP 4G Dome (AS-4G-3MP-DM)',
    category: 'Special Camera',
    price: 0,
    description: 'A standalone 4G dome camera that supports cloud storage and two-way communication. Main Highlights: 3MP Resolution, 4G Support, Micro SD',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-035',
    name: '3 MP 4G Bullet (AS-4G-3MP-BT)',
    category: 'Special Camera',
    price: 0,
    description: 'A 4G bullet camera with robust IR distance and H.265 compression for efficient storage. Main Highlights: 3MP Resolution, 4G Support,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-036',
    name: 'CP PLUS AI AHD DOME 2 .4MP NORMAL LED 4IN 1MIC',
    category: 'AHD Camera',
    price: 660,
    description: 'High performance CP PLUS AI AHD DOME 2 .4MP NORMAL LED 4IN 1MIC from CP Plus. Main Highlights: 2.4MP, 4MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-037',
    name: 'CP PLUS AI AHD BULLET 2.4MP NORMAL LED 4IN MIC',
    category: 'AHD Camera',
    price: 660,
    description: 'High performance CP PLUS AI AHD BULLET 2.4MP NORMAL LED 4IN MIC from CP Plus. Main Highlights: 2.4MP, 4MP, Bullet,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-038',
    name: 'CP PLUS AI AHD DOME 2 .4MP STARLIGHT LED 4IN MIC',
    category: 'AHD Camera',
    price: 780,
    description: 'High performance CP PLUS AI AHD DOME 2 .4MP STARLIGHT LED 4IN MIC from CP Plus. Main Highlights: 2.4MP, 4MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-039',
    name: 'CP PLUS AI AHD BULLET 2.4 MP STARLIGHT LED 4IN1 MIC',
    category: 'AHD Camera',
    price: 780,
    description: 'High performance CP PLUS AI AHD BULLET 2.4 MP STARLIGHT LED 4IN1 MIC from CP Plus. Main Highlights: Bullet, Starlight,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-040',
    name: 'CP PLUS AI AHD DOME 5MP STARLIGHT LED 4IN1 MIC',
    category: 'AHD Camera',
    price: 900,
    description: 'High performance CP PLUS AI AHD DOME 5MP STARLIGHT LED 4IN1 MIC from CP Plus. Main Highlights: 5MP, Dome, Starlight,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-041',
    name: 'CP PLUS AI AHD BULLET 5MP STARLIGHT LED 4IN 1 MIC',
    category: 'AHD Camera',
    price: 900,
    description: 'High performance CP PLUS AI AHD BULLET 5MP STARLIGHT LED 4IN 1 MIC from CP Plus. Main Highlights: 5MP, Bullet,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-042',
    name: 'CP PLUS AI IP 4MP STARLIGHT DOME PLASTIC WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1020,
    description: 'High performance CP PLUS AI IP 4MP STARLIGHT DOME PLASTIC WITH AUDIO POE BOARD from CP Plus. Main Highlights: 4MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-043',
    name: 'CP PLUS AI IP 4MP STARLIGHT BULLET PLASTIC WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1020,
    description: 'High performance CP PLUS AI IP 4MP STARLIGHT BULLET PLASTIC WITH AUDIO POE BOARD from CP Plus. Main Highlights: 4MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-044',
    name: 'CP PLUS AI IP 5MP STARLIGHT PLASTIC DOME WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1140,
    description: 'High performance CP PLUS AI IP 5MP STARLIGHT PLASTIC DOME WITH AUDIO POE BOARD from CP Plus. Main Highlights: 5MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-045',
    name: 'CP PLUS AI IP 5MP STARLIGHT BULLET PLASTIC WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1140,
    description: 'High performance CP PLUS AI IP 5MP STARLIGHT BULLET PLASTIC WITH AUDIO POE BOARD from CP Plus. Main Highlights: 5MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-046',
    name: 'CP PLUS AI IP 5MP STARLIGHT DOME METAL WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1380,
    description: 'High performance CP PLUS AI IP 5MP STARLIGHT DOME METAL WITH AUDIO POE BOARD from CP Plus. Main Highlights: 5MP,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-047',
    name: 'CP PLUS AI 5MP STARLIGHT METAL BULLET WITH AUDIO POE BOARD',
    category: 'IP Camera',
    price: 1380,
    description: 'High performance CP PLUS AI 5MP STARLIGHT METAL BULLET WITH AUDIO POE BOARD from CP Plus. Main Highlights: 5MP, Bullet,',
    image: getImage('product-camera'),
  },
  {
    id: 'prod-048',
    name: 'CP PLUS AI NVR PRO 10CH',
    category: 'NVR',
    price: 2700,
    description: 'High performance CP PLUS AI NVR PRO 10CH from CP Plus. Main Highlights: NVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-049',
    name: 'CP PLUS AI NVR PRO 16CH',
    category: 'NVR',
    price: 2940,
    description: 'High performance CP PLUS AI NVR PRO 16CH from CP Plus. Main Highlights: NVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-050',
    name: 'CP PLUS AI NVR PRO 32CH DUAL SATA',
    category: 'NVR',
    price: 7500,
    description: 'High performance CP PLUS AI NVR PRO 32CH DUAL SATA from CP Plus. Main Highlights: NVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-051',
    name: 'CP PLUS AI DVR PRO 4CH',
    category: 'DVR',
    price: 2700,
    description: 'High performance CP PLUS AI DVR PRO 4CH from CP Plus. Main Highlights: DVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-052',
    name: 'CP PLUS AI DVR PRO 8CH',
    category: 'DVR',
    price: 3060,
    description: 'High performance CP PLUS AI DVR PRO 8CH from CP Plus. Main Highlights: DVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-053',
    name: 'CP PLUS AI DVR PRO 16CH.',
    category: 'DVR',
    price: 4140,
    description: 'High performance CP PLUS AI DVR PRO 16CH. from CP Plus. Main Highlights: DVR, Security.',
    image: getImage('product-storage'),
  },
  {
    id: 'prod-054',
    name: 'CP PLUS AI POE SWITCH 4CH',
    category: 'Poe Switch',
    price: 1500,
    description: 'High performance CP PLUS AI POE SWITCH 4CH from CP Plus. Main Highlights: PoE, Switch.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-055',
    name: 'CP PLUS AI POE SWITCH 8CH',
    category: 'Poe Switch',
    price: 1980,
    description: 'High performance CP PLUS AI POE SWITCH 8CH from CP Plus. Main Highlights: PoE, Switch.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-056',
    name: 'CP PLUS AI 3+1WAIR 90MTR COPER',
    category: 'Wire',
    price: 900,
    description: 'High performance CP PLUS AI 3+1WAIR 90MTR COPER from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-057',
    name: 'CP PLUS AI CAT-6 100MTR ALOY',
    category: 'Wire',
    price: 1020,
    description: 'High performance CP PLUS AI CAT-6 100MTR ALOY from CP Plus. Main Highlights: Cat-6, Security.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-058',
    name: 'CP PLUS AI CAT-6 100MTR COPER',
    category: 'Wire',
    price: 1860,
    description: 'High performance CP PLUS AI CAT-6 100MTR COPER from CP Plus. Main Highlights: Cat-6, Security.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-059',
    name: 'CP PLUS AI CAT-6 FULL COPPER 300MTR',
    category: 'Wire',
    price: 7440,
    description: 'High performance CP PLUS AI CAT-6 FULL COPPER 300MTR from CP Plus. Main Highlights: Cat-6, Security.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-060',
    name: 'CP PLUS AI CAT-5 2PEAR WAIR COPER 250 MTR',
    category: 'Wire',
    price: 2640,
    description: 'High performance CP PLUS AI CAT-5 2PEAR WAIR COPER 250 MTR from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-061',
    name: 'PVC BOX 4 X4 SQURE FRESS',
    category: 'Rack',
    price: 19,
    description: 'High performance PVC BOX 4 X4 SQURE FRESS from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-062',
    name: 'PVC BOX 5 X5 SQURE',
    category: 'Rack',
    price: 24,
    description: 'High performance PVC BOX 5 X5 SQURE from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-063',
    name: 'PVC BOX ROUND 4 X5 SQUER',
    category: 'Rack',
    price: 22,
    description: 'High performance PVC BOX ROUND 4 X5 SQUER from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-064',
    name: 'POE RACK BIG METAL 2 YOU RACK',
    category: 'Rack',
    price: 420,
    description: 'High performance POE RACK BIG METAL 2 YOU RACK from CP Plus. Main Highlights: PoE, Rack.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-065',
    name: '4U FOLDABLE METAL RACK',
    category: 'Rack',
    price: 708,
    description: 'High performance 4U FOLDABLE METAL RACK from CP Plus. Main Highlights: Rack, Security.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-066',
    name: 'CP PLUS AI 4G ROUTER 5G SIM SUPPORTED',
    category: 'Accessories',
    price: 1500,
    description: 'High performance CP PLUS AI 4G ROUTER 5G SIM SUPPORTED from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-067',
    name: 'BNC CONNECTOR',
    category: 'Accessories',
    price: 12,
    description: 'High performance BNC CONNECTOR from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-068',
    name: 'RC CONNECTOR',
    category: 'Accessories',
    price: 4,
    description: 'High performance RC CONNECTOR from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-069',
    name: 'RJ485 CONNECTOR',
    category: 'Accessories',
    price: 420,
    description: 'High performance RJ485 CONNECTOR from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-070',
    name: 'power supply',
    category: 'Power Supply',
    price: 480,
    description: 'High performance power supply from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-071',
    name: 'power supply 4ch',
    category: 'Power Supply',
    price: 540,
    description: 'High performance power supply 4ch from CP Plus. Main Highlights: Security, CP Plus.',
    image: getImage('product-accessories'),
  },
  {
    id: 'prod-072',
    name: 'CP Plus testing',
    category: 'AHD Camera',
    price: 456,
    description: 'The 2.4MP IR Dome Camera is a high-resolution surveillance camera designed to provide reliable video monitoring in various indoor and',
    image: getImage('product-camera'),
  }
];

export const categories: ProductCategory[] = [
    'AHD Camera',
    'IP Camera',
    'Special Camera',
    'DVR',
    'NVR',
    'Poe Switch',
    'Wire',
    'Rack',
    'Power Supply',
    'Accessories',
    'Video Door Phone',
    'Biometric Device',
];
